# support reading from .env file
spring.config.import=file:../.env[.properties],file:.env[.properties]
spring.application.name=solar-watch
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_PATH}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
codecool.app.jwtSecret=${JWT_SECRET}
codecool.app.jwtExpirationMs=86400000
codecool.app.api.key=${API_KEY}
